//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JUUL_Export
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int Store_ID { get; set; }
        public string Store_Number { get; set; }
        public string Installation_ID { get; set; }
        public int Company_ID { get; set; }
        public string Store_Name { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<byte> Is24Hours { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> Brand { get; set; }
        public Nullable<byte> CStore { get; set; }
        public Nullable<byte> Diesel { get; set; }
        public Nullable<byte> Carwash { get; set; }
        public Nullable<int> District { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<byte> PollFuelPrices { get; set; }
        public Nullable<byte> Gaming { get; set; }
        public Nullable<byte> HotFood { get; set; }
        public Nullable<byte> ColdFood { get; set; }
        public Nullable<byte> Restaraunt { get; set; }
    }
}
